# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: nextbus-ttc 0.0.1 ruby lib

Gem::Specification.new do |s|
  s.name = "nextbus-ttc"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jesse Buchanan", "Greg Sterndale"]
  s.date = "2014-12-09"
  s.description = "NextBus API client for TTC"
  s.email = "hello@jessebuchanan.ca"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md",
    "README.original.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.md",
    "README.original.md",
    "Rakefile",
    "VERSION",
    "doc/ERM.graffle",
    "doc/MBTA_XML_Feed_Trial_Docs_13Nov09-1.pdf",
    "lib/attr_with_default.rb",
    "lib/instantiate_with_attrs.rb",
    "lib/nextbus.rb",
    "lib/nextbus/agency.rb",
    "lib/nextbus/client.rb",
    "lib/nextbus/direction.rb",
    "lib/nextbus/mash_extensions.rb",
    "lib/nextbus/prediction.rb",
    "lib/nextbus/report.rb",
    "lib/nextbus/route.rb",
    "lib/nextbus/stop.rb",
    "lib/nextbus/string_extensions.rb",
    "lib/nextbus/vehicle.rb",
    "nextbus-ttc.gemspec",
    "test/fixtures/agency_list.xml",
    "test/fixtures/error.xml",
    "test/fixtures/predictions.xml",
    "test/fixtures/predictions_for_multi_stops.xml",
    "test/fixtures/route_config.xml",
    "test/fixtures/route_list.xml",
    "test/fixtures/vehicle_locations.xml",
    "test/helper.rb",
    "test/stub_chain_mocha.rb",
    "test/unit/test_agency.rb",
    "test/unit/test_attr_with_default.rb",
    "test/unit/test_client.rb",
    "test/unit/test_direction.rb",
    "test/unit/test_instantiate_with_attrs.rb",
    "test/unit/test_mash_extensions.rb",
    "test/unit/test_nextbus.rb",
    "test/unit/test_prediction.rb",
    "test/unit/test_report.rb",
    "test/unit/test_route.rb",
    "test/unit/test_stop.rb",
    "test/unit/test_string_extensions.rb",
    "test/unit/test_vehicle.rb",
    "vendor/cache/addressable-2.3.6.gem",
    "vendor/cache/builder-3.2.2.gem",
    "vendor/cache/byebug-3.5.1.gem",
    "vendor/cache/coderay-1.1.0.gem",
    "vendor/cache/columnize-0.9.0.gem",
    "vendor/cache/debugger-linecache-1.2.0.gem",
    "vendor/cache/descendants_tracker-0.0.4.gem",
    "vendor/cache/faraday-0.9.0.gem",
    "vendor/cache/git-1.2.8.gem",
    "vendor/cache/github_api-0.12.2.gem",
    "vendor/cache/hashie-3.3.2.gem",
    "vendor/cache/highline-1.6.21.gem",
    "vendor/cache/httparty-0.13.3.gem",
    "vendor/cache/jeweler-2.0.1.gem",
    "vendor/cache/json-1.8.1.gem",
    "vendor/cache/jwt-1.2.0.gem",
    "vendor/cache/metaclass-0.0.4.gem",
    "vendor/cache/method_source-0.8.2.gem",
    "vendor/cache/mini_portile-0.6.1.gem",
    "vendor/cache/mocha-1.1.0.gem",
    "vendor/cache/multi_json-1.10.1.gem",
    "vendor/cache/multi_xml-0.5.5.gem",
    "vendor/cache/multipart-post-2.0.0.gem",
    "vendor/cache/nokogiri-1.6.5.gem",
    "vendor/cache/oauth2-1.0.0.gem",
    "vendor/cache/pry-0.10.1.gem",
    "vendor/cache/pry-byebug-2.0.0.gem",
    "vendor/cache/rack-1.5.2.gem",
    "vendor/cache/rake-10.4.2.gem",
    "vendor/cache/rdoc-4.1.2.gem",
    "vendor/cache/slop-3.6.0.gem",
    "vendor/cache/thread_safe-0.3.4.gem"
  ]
  s.homepage = "http://github.com/jbinto/nextbus-ttc"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.2.2"
  s.summary = "NextBus API client for TTC"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<httparty>, [">= 0"])
      s.add_runtime_dependency(%q<hashie>, [">= 0"])
      s.add_runtime_dependency(%q<mocha>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<pry-byebug>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<httparty>, [">= 0"])
      s.add_dependency(%q<hashie>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<pry-byebug>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<httparty>, [">= 0"])
    s.add_dependency(%q<hashie>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<pry-byebug>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

